### ISSUE TITLE
Step 15. デバイス情報の編集 - ルーティング引数の引数の型について

### ISSUE THREAD

**Issue by lensouko** [jsakamoto/self-learning-materials-for-blazor-jp#1]
＞なお、このようにURL 引数を受け取るプロパティの型は、
＞今日時点のBlazor ではstring 型に限定されているようです。
とありますが、
```
@page "/counter/{amt:int}"
    [Parameter]
    private int amt { get; set; } = 1;
```
これでintでの受け取りができています。
他の型は試していませんが……

**Comment by jsakamoto** [comment]
なるほど、ルーティング引数定義に `:型名` で string 型以外でもバインドできますね。

確認したところ、他にも `bool` や `guid` などの型名が指定できるようですね (下記)。

https://github.com/aspnet/Blazor/blob/dev/src/Microsoft.AspNetCore.Blazor/Routing/RouteConstraint.cs#L45

追って自習書も改訂したいと思います。  
お知らせいただいて助かります、ありがとうございます! 👍

**Comment by jsakamoto** [comment]
本件に対応した [0.3.0-b](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/0.3.0-b) をリリースしました。

これにて本 Issue は close します。  
ありがとうございました!
