### ISSUE TITLE
リリースページの zip ファイルにソースコードが含まれていません

### ISSUE THREAD

**Issue by pecochappy** [jsakamoto/self-learning-materials-for-blazor-jp#10]
リリースページ
　https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases
から Self-Learning-Materials-for-Blazor-JP-v.5.0.zip をダウンロードしてみたのですが、
src ディレクトリには「old-release-document.md」というファイルのみが存在していました。

私が何か勘違いしているだけなのかもしれず、そうでしたら大変申し訳ありません。。。
大変お手数お掛けしますが、ご確認いただけますと幸いです。

**Comment by jsakamoto** [comment]
@pecochappy 
ご連絡ありがとうございます!

本当ですね、酷い Zip ファイルになってしまってますね 😢

Zip ファイルのビルドに失敗していたのに気づかず更新してしまったようです。
ご報告いただきありがとうございます。大変助かります。
日付が今日のうちには、修正・更新したいと思います。

**Comment by jsakamoto** [comment]
@pecochappy 先ほど、今一度パッケージを作り直し、Release ページに再アップロードしました。

ご確認いただければと思います。

**Comment by pecochappy** [comment]
迅速に対応して頂きありがとうございます。
各ステップにソースファイルが解凍されましたので大丈夫です！
※ビルド・実行できることは step-01-boilerplate のみ確認しました。

Blazor に入門してみたかったので、ステップアップして
自習できる日本語教材は本当にありがたいです。

※Qiita Advent Calendar も楽しみにしております。

**Comment by jsakamoto** [comment]
@pecochappy 報告いただきありがとうございました!

こうしてお知らせなかったら、ずっとこのまま放置されていたかもしれません 💧

貢献ありがとうございます!
