### ISSUE TITLE
button の type 指定について

### ISSUE THREAD

**Issue by pecochappy** [jsakamoto/self-learning-materials-for-blazor-jp#11]
お世話になります、先日リリースページの zip ファイルをご対応頂いた者です。
お陰様で自習書の学習が一通り完了しました。
僭越ながらその際に気づいた点をフィードバック致します。

Blazorアプリケーションプログラミング自習書-v.5.0.pdf の
P.54 の項番 4 にて追加するソースコード

```
@if (OnClickDelete != null)
{
    <button class="button delete-button" @onclick="OnDelete">削除</button>
}
```
をソースに適用してみたところ、OnDelete が実行された後に続けて OnOK も実行されました。
(confirm が yes であるかどうかに関わらず)

自習書ではなくソースコードを確認しますと以下のように「type="button"」の指定がありました。

```
@if (OnClickDelete != null)
{
    <button class="button delete-button" type="button" @onclick="OnDelete">削除</button>
}
```
このコードであれば OnOK が続けて実行されることはありませんでしたので、
「type="button"」の指定は必須と思われました。

※指定しない場合は type="submit" 扱いとなりバリデーションが動作している、ということでしょうか？

**Comment by jsakamoto** [comment]
@pecochappy フィードバックありがとうございます!

> ※指定しない場合は type="submit" 扱いとなりバリデーションが動作している、ということでしょうか？

まさしくそのとおりと思います。

本件、自習書の誤記ということで、追って訂正版をリリースしたいと思います。

**Comment by jsakamoto** [comment]
[修正版 (v.5.0b) をリリース](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/doc%2F5.0b)しました。

**Comment by pecochappy** [comment]
自習書の該当箇所の記述が修正されたことを確認致しました。
ご対応頂きありがとうございます。
