### ISSUE TITLE
Windows 10 IIS 用のフォルダー発行方法について

### ISSUE THREAD

**Issue by shinta0806** [jsakamoto/self-learning-materials-for-blazor-jp#13]
第 21 章のプロジェクトについて、Visual Studio の F5 デバッグ実行で問題なく動かすことができたのですが、このプロジェクトを Windows 10 の IIS で動かすためのフォルダー発行がうまくいかず、やり方を教えて頂くことは可能でしょうか。

【試した内容】

・BlazorWOL.Server をフォルダー（publish）へ発行
・publish フォルダーに IIS がアクセスできるよう、IUSR と IIS_IUSRS の読み取りと実行を許可
・IIS マネージャーでサイトに publish フォルダーを追加
・Web サイトを参照
→HTTP エラー 500.19 - Internal Server Error
→エラーコード 0x8007000d
→構成ファイル web.config

![publish](https://user-images.githubusercontent.com/7196473/101971801-56cd4500-3c77-11eb-89db-9bbefcf296cb.png)
![site](https://user-images.githubusercontent.com/7196473/101971817-749aaa00-3c77-11eb-999c-e2278a3538a4.png)
![sitebind](https://user-images.githubusercontent.com/7196473/101971830-8da35b00-3c77-11eb-8297-6b3fd7f2a988.png)
![err](https://user-images.githubusercontent.com/7196473/101971848-aad82980-3c77-11eb-9fa3-53121624f1b9.png)

【生成された web.config の内容】

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <location path="." inheritInChildApplications="false">
	    <system.webServer>
	      <handlers>
	        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
	      </handlers>
	      <aspNetCore processPath=".\BlazorWOL.Server.exe" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
	    </system.webServer>
	  </location>
	</configuration>
	

お手数おかけ致しますが、ご教示頂ければ幸いです。

**Comment by shinta0806** [comment]
自己解決しました。
一度管理者権限で発行したからか理由は分からないのですが、上記で動くようになりました。
お騒がせいたしました。

**Comment by jsakamoto** [comment]
@shinta0806 とりあえず解決はされたようでよかったです。
