### ISSUE TITLE
Step5のClockListComponent.razorの記述について

### ISSUE THREAD

**Issue by tomokusaba** [jsakamoto/self-learning-materials-for-blazor-jp#14]
![image](https://user-images.githubusercontent.com/46523924/232971064-278a4a9c-c4d1-46d5-a634-ebb7190eea63.png)
上記の赤線部分について
ToString()がToSting()になっているのはデバッグさせるための意図的な記述でしょうか？

**Comment by jsakamoto** [comment]
@tomokusaba 連絡ありがとうございます。こちらは単純にタイポです (ソースコードから Word に貼り付け後、整形の際か、あるいはタッチデバイスの誤タップなどで誤字に至ったものと想像されます)。
追って訂正版をリリースしたいと思います。
本テキストで自習されている方は、このようなテキストの間違いに遭遇されても、逐一このように Issue をあげてくださるわけではありませんようですので (手間ですからね...)、このようなお知らせは大変助かります。
お知らせいただきありがとうございました、訂正完了まで暫しお時間ください。

**Comment by jsakamoto** [comment]
@tomokusaba  訂正完了し、v.7.0.1 をリリースしました。ご確認いただければと思います。
(当方の手違いでまだ修正がなっていなかった場合は、お気軽に本 Issue を再オープンください)
