### ISSUE TITLE
Step 16の手順１の開き括弧と閉じ括弧の数が違います。

### ISSUE THREAD

**Issue by tomokusaba** [jsakamoto/self-learning-materials-for-blazor-jp#15]
![image](https://user-images.githubusercontent.com/46523924/233011032-8dfe570b-66ad-4c97-bb90-6d436cc820af.png)

赤線部分の開き括弧と閉じ括弧の数が違うようです。
本教材で自習させているのですが気づいた点をあげさせていただいています。

**Comment by jsakamoto** [comment]
@tomokusaba 連絡ありがとうございます、大変助かります。
訂正完了まで暫しお時間ください。

**Comment by jsakamoto** [comment]
@tomokusaba  訂正完了し、v.7.0.1 をリリースしました。ご確認いただければと思います。
この度は誤記についてのご連絡ありがとうございます。個人活動として限られた時間で作成している自習テキストということもあり、誤記・タイポのチェックには限界もありまして、このようにお知らせ頂けるのは大変ありがたい次第です。もちろん、本自習書を利用されている方々もお忙しいでしょうから、語誤記に気づいたとしてもなかなか逐一 Issue 立てていただくことも難しいことと理解はしております。そのような背景下、このように Issue にてご連絡くださいましたこと、改めて御礼申し上げます。
(当方の手違いでまだ修正がなっていなかった場合は、お気軽に本 Issue を再オープンください)
