### ISSUE TITLE
P.71 ClockService.UpdateClockAsync()の記述について

### ISSUE THREAD

**Issue by tomokusaba** [jsakamoto/self-learning-materials-for-blazor-jp#16]
Clockクラスを参照しているので現在idが小文字で書かれていますがIdとして

```
await httpClient.PutAsJsonAsync($"api/clocks/{clock.Id}", clock);
```

になるかと思います。

**Comment by jsakamoto** [comment]
@tomokusaba 毎度、誤記のご連絡ありがとうございます! 修正版 (8.0.1) をリリースしました。

- https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/doc%2F8.0.1
