### ISSUE TITLE
Is there an English Version?

### ISSUE THREAD

**Issue by LuohuaRain** [jsakamoto/self-learning-materials-for-blazor-jp#5]
I am not good at Japanese, wish there could be an English version. Thanks.

**Comment by jsakamoto** [comment]
Thank you for contact to me!

By the way, I have not enough time to create English version, at least until passed by July.

I'm interested in creating English version, but I can not promise it.

There are already English version great samples/texts of Blazor on the internet.

- https://github.com/dotnet-presentations/blazor-workshop
- https://github.com/brianlowe/blazor-tour-of-heroes

Are those helpful for you?

**Comment by LuohuaRain** [comment]
Thank you so much, and I found your repo is the newest Blazor documents on Github so I open this issue. Haha
