### ISSUE TITLE
Step17 NotFoundページのレイアウト指定が誤っている

### ISSUE THREAD

**Issue by cm-iwata** [jsakamoto/self-learning-materials-for-blazor-jp#6]
>Step 17. タイトルヘッダの追加 - レイアウト

でNotFoundページを以下のように修正しています。

```
<NotFound>
    <LayoutView DefaultLayout="typeof(MainLayout)">
        <p>Sorry, there's nothing at this address.</p>
    </LayoutView>
</NotFound>
```

こちらですが、指定するのは`DefaultLayout`ではなく`Layout`が正解ではないでしょうか？
`DefaultLayout`を指定するとNotFoundページが表示できませんでした。

参考
https://docs.microsoft.com/ja-jp/aspnet/core/blazor/layouts?view=aspnetcore-3.1

**Comment by jsakamoto** [comment]
ご報告ありがとうございます!
ご指摘のとおり、テキストが誤っておりました。

README の "サポート" のところにもなにげに書いておりますが、隙間時間で作成・保守している自習書であるため、やはり私一人では目が届いていないところが多く、このようなご報告は本当に大変助かります。

おかげさまで[修正を完了](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/commit/661a8ff4bcd05f3a5ba91f008070a91eb94eb5e8)し、[修正版をリリース](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/doc%2F3.2.0-preview1.20073.1b)できました。

どうもありがとうございました!
