### ISSUE TITLE
文書に不要な空白があります

### ISSUE THREAD

**Issue by k4i-makino** [jsakamoto/self-learning-materials-for-blazor-jp#7]
PDF の P.39(STEP 15)の EditDevice の追加部分が
> [名前(N)] に "EditDevice " と入力してから

となっており, "EditDevice" の後ろに不要な空白があります.

なお, この部分をコピペして進めても Visual Studio で作成する際はこの手の空白はトリムされるので,
影響は小さいかと思います.

**Comment by jsakamoto** [comment]
コミット 6f99f8e で対応しました。

また今回、Blazor v.3.2.0 Preview 3 20168.3 への対応を実施しましたので、修正後の自習書は[こちら](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/doc%2F3.2.0-preview3.20168.3) での配布となります。

不具合報告、ありがとうございました!
