### ISSUE TITLE
DevicesComponent.razor のメンバーフィールドがいつの間にか初期化されていました

### ISSUE THREAD

**Issue by k4i-makino** [jsakamoto/self-learning-materials-for-blazor-jp#8]
STEP 8 のコードでは DevicesComponent.razor のメンバーフィールド Devices は
``` cs
IEnumerable<Device> Devices;
```
となっていますが, STEP 9 では
``` cs
IEnumerable<Device> Devices = new Device[0];
```
となっていました.

本筋とは関係のない部分で詳細な記載は不要な箇所かもしれませんが,
PDF を頭から読みながら自分で実装して行った際に STEP 8 のコードのままだと,
ダミーデータを削除してサーバー側からデータを取得する STEP になった段階で表示がされなくなりました.

STEP 8 の 7. にある実装画像の Devices の部分を STEP 9 のような形にしておくのはどうでしょうか？

**Comment by jsakamoto** [comment]
@k4i-makino お知らせありがとうございます!

どうしても片手間で保守しているため、このような抜け・漏れ、誤りが出てしまっているようで、その点、こうしてご報告いただけると大変助かります。

まだちょっと、今すぐには修正に取りかかれないのですが、なるべく早めに着手・修正しようと思います (別にお知らせ頂いている #7 も含め)。

暫しお時間下さい!

**Comment by jsakamoto** [comment]
コミット 893a0d0 で対応しました。

ソースコードの変更履歴も、[こちら](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/commit/4c90772bd49655f7aaf67434eed84a412bf5dda3#diff-7487e981af11f1f421f447a567292abeR18)のとおり、修正後の自習書の手順にあうように修正してあります。

また今回、Blazor v.3.2.0 Preview 3 20168.3 への対応を実施しましたので、修正後の自習書は[こちら](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/doc%2F3.2.0-preview3.20168.3) での配布となります。

不具合報告、大変助かりました、ありがとうございました! 👍
