### ISSUE TITLE
Device.cs の不要な@

### ISSUE THREAD

**Issue by AkimasaKonishi** [jsakamoto/self-learning-materials-for-blazor-jp#9]
Step 11 (P.25) の Device.cs のソースコードに、不要な”@”があります。
```
@using System;
@using System.ComponentModel.DataAnnotations;

namespace BlazorWOL.Shared
{
    ....
```

**Comment by jsakamoto** [comment]
@AkimasaKonishi  ご報告ありがとうございます!
コミット 3e380282a42aef0605a03e3a471d1922618c2f7a で修正完了しまして、[v.3.2.0b としてリリース](https://github.com/jsakamoto/self-learning-materials-for-blazor-jp/releases/tag/doc%2F3.2.0b)しました。

他の Issue にも書いていますが、隙間時間で作成・保守している自習書であるため、やはり私一人では目が届いていないところが多く、このようなご報告は本当に大変助かります。

おかげさまで修正版をリリースできました。

どうもありがとうございました!
